[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "3BJ7Lxq6ayB6P5JrBkNDWDL9EpWv7TYXn8qQjkyV995k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rvnadela/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
